### ISSUE TITLE
Would be nice to add basic config or cache for closed windows

### ISSUE THREAD

**Issue by hrasekj** [coffebar/hyprland-per-window-layout#11]
This daemon works great, but only for windows that stay opened. I wonder if there could be option to have a config with list of window classes that should be set the keyboard layout to when open. 

Or possibly remember last used keyboard layout after window is closed. For instance i'm using Czech layout only in Slack and email client, but my primary layout is english.

**Comment by coffebar** [comment]
The idea looks interesting.
I made a superficial analysis of what needs to be done to implement such functionality.

First, you need to find a configuration format that will be convenient for parsing in rust and for users.
Location of this file should be at `$HOME/.config/hyprland-per-window-layout/custom-defaults.yml`

I believe it needs to contain pairs of `class - layout`

Second, the program needs to parse this file at startup.

thirdly, wait for consecutive pairs of events like this:

> E:'activewindow' D:'Alacritty,abc@crab:~'
> E:'activewindowv2' D:'55c7ed3618c0'

If Alacritty in this example matches the class in the config and the address 55c7ed3618c0 is new, then try to switch layout

**Comment by hrasekj** [comment]
Yes, sounds good. What about toml? Rust already know how to parse it and it is wery simple for users too.

Also when parsing the config, there should be validation of layout, classes does not need to be validated, they would just not mach.

**Comment by coffebar** [comment]
If we go into details, `hyprctl switchxkblayout` operates indexes of the layouts. So we can't say "switch to DE", but we can set index 1, where 0 is english(US) and 1 is DE in this example hyprland config:
```
input {
  kb_layout = us,de
...
```

I have an example toml file for config:

```toml
[[default-layouts]]
1 = [
    "firefox",
    "org.telegram.desktop",
]
```
Which means to use second language for firefox and telegram

**Comment by hrasekj** [comment]
I like that config example. But i don't think it's good idea use index directly in config. I can imagine someone change the layout order or add new layout to that index and then the config will stop work.

**Comment by coffebar** [comment]
the program does not know the names of languages and does not operate with them, only indexes

**Comment by hrasekj** [comment]
So the `hyprctl getoption input:kb_layout` will not work?

**Comment by coffebar** [comment]
this should give info, that will be relevant until the user changes the file again

**Comment by coffebar** [comment]
I made a [branch](https://github.com/coffebar/hyprland-per-window-layout/tree/patch11) 
with a solution that works for me. 
You can checkout this branch and test it with me.

Here is my config file:

~/.config/hyprland-per-window-layout/options.toml
```toml
keyboards = [
  "at-translated-set-2-keyboard",
]

[[default_layouts]]
1 = [
    "org.telegram.desktop",
]
```

keyboards taken from `hyprctl devices`

keyboard names required to change layout 

![image](https://github.com/coffebar/hyprland-per-window-layout/assets/3100053/535100ee-f4f7-476f-a857-02a1fbe8377a)

window class - from `hyprctl clients`
