### ISSUE TITLE
[BUG] Can't run in tmux

### ISSUE THREAD

**Issue by ProMix0** [coffebar/hyprland-per-window-layout#14]
**Describe the bug**
hyprland-per-window-layout can't be run inside of tmux

**To Reproduce**
Start tmux and run hyprland-per-window-layout inside it

**Expected behavior**
hyprland-per-window-layout should run

**Linux Distro (please complete the following information):**
 - Gentoo. Latest hyprland-per-window-layout release

**Additional context**
```sh
# RUST_BACKTRACE=full hyprland-per-window-layout
thread 'main' panicked at src/main.rs:56:61:
called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)
stack backtrace:
   0:     0x55acd61f1f6c - <unknown>
   1:     0x55acd621a7fc - <unknown>
   2:     0x55acd61ef4fe - <unknown>
   3:     0x55acd61f1d54 - <unknown>
   4:     0x55acd61f32d3 - <unknown>
   5:     0x55acd61f2ff4 - <unknown>
   6:     0x55acd61f3855 - <unknown>
   7:     0x55acd61f3751 - <unknown>
   8:     0x55acd61f2496 - <unknown>
   9:     0x55acd61f34a2 - <unknown>
  10:     0x55acd60f7df5 - <unknown>
  11:     0x55acd60f82d3 - <unknown>
  12:     0x55acd60ff674 - <unknown>
  13:     0x55acd6106313 - <unknown>
  14:     0x55acd61065f9 - <unknown>
  15:     0x55acd61eafbb - <unknown>
  16:     0x55acd6100305 - <unknown>
  17:     0x7ff7360b2c8a - <unknown>
  18:     0x7ff7360b2d45 - __libc_start_main
  19:     0x55acd60f8591 - <unknown>
  20:                0x0 - <unknown>
```

**Comment by coffebar** [comment]
What this command show if you run it in tmux?

`hyprctl getoption input:kb_layout -j`

**Comment by ProMix0** [comment]
```sh
hyprctl getoption input:kb_layout -j

{
    "option": "input:kb_layout",
    "int": -9223372036854775807,
    "float": -340282346638528859811704183484516925440.00000,
    "str": "us,ru",
    "data": "0x0",
    "set": true
}
```

Output after reboot, which fix the problem

But before already running instance was consuming 100% CPU, so I'll try to look after that

**Comment by ProMix0** [comment]
Restarting hyprland causes to that:
![image](https://github.com/coffebar/hyprland-per-window-layout/assets/54300969/390cbcd7-a638-43ff-b427-c5a358eb1d15)

Logs:
`hyprland-per-wi[958]: Another instance is running.`

**Comment by ProMix0** [comment]
Do you mean latter instance lost connection with hyprland and prevent new instance to run?

Maybe hyprland-per-window-layout should exit on hyprland shutdown?

**Comment by coffebar** [comment]
Every process started by hyprland will be automatically killed on its exit as a child process

**Comment by ProMix0** [comment]
Yes, I agree, it should. But it don't in that case

Checked in tty htop, hyprland-per-window-layout stays after exiting, using 100% CPU

I guess it hyprland issue, but maybe not. Anyway I'll investigate later

P.S. Hyprland version - 0.32.3 gentoo
