### ISSUE TITLE
Keeping track of keyboard variants

### ISSUE THREAD

**Issue by NiloDrumond** [coffebar/hyprland-per-window-layout#15]
**Is your feature request related to a problem? Please describe.**
I have used US to write code, and US-intl to write in Portuguese for years, so my hypr.conf looks like this:
``` 
kb_layout = us,us
kb_variant = ,intl
```
I tested using for a while `kb_layout = us,br` with this tool and it worked perfectly, but I couldn't get used to the standard Brazilian keyboard, so it would be nice if this worked for variants too.

Currently, I find this tool behaving very weirdly with variants:
- Most of the time, if I change to the intl variant and go to another application, it goes to the default variant (as expect), but when I go back to the application I changed to intl, it goes back to default. So in short, it almost never saves the variant I was using.
- I say almost, because sometimes it also gets stuck on the intl variant, so no matter what app I go to, it stays on intl until I manually change back to the default variant.

I couldn't figure out why it happened on either case.

**Describe the solution you'd like**
The tool should keep track not only of the layout the person is using, but also the variant.

**Describe alternatives you've considered**
Not really much apart from trying to figure out what is going on in the code and trying to implement it myself.

My rust skills are lacking, but not zero, so I will see if I can implement this myself and open a PR. If you have any tips or maybe if you considered implementing this yourself and found a bump, let me know.

**Comment by coffebar** [comment]
To do this task, you need to examine the information that hyprctl provides and figure out how to obtain variant related to layouts. I didn't use any specific variants, so I don't know how it works and didn't test this case.

If you need some help with explaining how my code works, I will answer your questions. 

Obrigado.
