### ISSUE TITLE
Need help [BUG]

### ISSUE THREAD

**Issue by coffebar** [coffebar/hyprland-per-window-layout#18]
When start using, it's hard to notice any major issues, but after some time it is starting to messed up with layouts.
I need help from the community to fix this bug.

**Comment by paul-axe** [comment]
Hi. I also facing issues with layout changing. After the quick code review I think you forgot to update ACTIVE_LAYOUT values in the else branch.
https://github.com/coffebar/hyprland-per-window-layout/blob/e6023e4b6c3510843890ca37425b1ed2914da9cc/src/hyprland_event.rs#L127-L131

**Comment by coffebar** [comment]
This patch make sense to me, thanks. @paul-axe Do you want to open PR?

**Comment by paul-axe** [comment]
Yep, sure, here it is #19 
However I want to test it a bit more

**Comment by coffebar** [comment]
A new release has been published. Thanks
