### ISSUE TITLE
hyprland-per-window-layout fails on hyprland startup

### ISSUE THREAD

**Issue by ArkadyBuryakov** [coffebar/hyprland-per-window-layout#20]
**Describe the bug**
When I run hyprland-per-window-layout at hyprland startup using `exec-once` process stops for some reason.

When I run hyprland-per-window-layout manually after startup - it works as expected.

**To Reproduce**
1. Install and setup hyprland-per-window-layout according to [manual](https://github.com/coffebar/hyprland-per-window-layout/blob/main/README.md)
2. Logout
3. Login into hyprland session
4. Try to change keyboard layout
    - **Result:** all windows share same keyboard layout context
5. Check hyprland-per-window-layout process
    - **Result:** hyprland-per-window-layout is not running

**Expected behavior**
hyprland-per-window-layout is running and works normally.

**Linux Distro (please complete the following information):**
 - Arch
 - Hyprland 0.41.2 (extra)
 - hyprland-per-window-layout 2.11 (AUR)

**Additional context**
Workaround: delay hyprland-per-window-layout execution like this:
```bash
exec-once=sleep 2 && /usr/bin/hyprland-per-window-layout
```
Also I checked logs of hyprland, it seems that hyprland executes my `exec-once` statements before defining my keyboard layouts. Maybe this could be a root of the problem.

PS: I do not think that this degradation happened in 2.11 version. 
This happened after one of the latest hyprland updates.

**Comment by coffebar** [comment]
Try to setup it this way and reboot:
```
exec-once = RUST_LOG='debug' /usr/bin/hyprland-per-window-layout > /tmp/hyprland-per-window-layout.log 2>&1
```
Then show what you have in /tmp/hyprland-per-window-layout.log

**Comment by ArkadyBuryakov** [comment]
Hi! For some reason I cannot reproduce this bug right now. It was persistent last few days and earlier today.

I'll work with this config for some time. If during this week bug will be reproduced - I'll attach a log, otherwise I'll close this issue.

**Comment by ArkadyBuryakov** [comment]
Got it! For some reason it happens when I start session with external monitor. I suppose it causes hyprland to slow down for some reason. Here is log:
```
[2024-07-10T17:59:52Z DEBUG hyprland_per_window_layout::hyprland_event] Status code is 5
[2024-07-10T17:59:52Z DEBUG hyprland_per_window_layout] input:kb_layout: Hyprland IPC didn't respond in time
    
    Couldn't read (5)
    
thread 'main' panicked at src/main.rs:59:61:
called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by coffebar** [comment]
**hyprland-per-window-layout** needs to get keyboard layouts from hyprland to work. The problem is following cli command failed:
```bash
hyprctl getoption input:kb_layout -j
```
with message:

> Hyprland IPC didn't respond in time

You should open an issue on hyprland

**Comment by coffebar** [comment]
@ArkadyBuryakov You can remove sleep from config, but hyprland still has this issue, and it will be shown in stdout
