### ISSUE TITLE
[BUG] issues with kb_file

### ISSUE THREAD

**Issue by c0h2r** [coffebar/hyprland-per-window-layout#4]
**Describe the bug**
1. Due to [how the program checks for layouts](https://github.com/coffebar/hyprland-per-window-layout/blob/main/src/main.rs#L42), it refuses to run when `kb_file` is used instead of `kb_layout`.
2. Also, because of [adding this hard-coded layout](https://github.com/coffebar/hyprland-per-window-layout/blob/main/src/main.rs#L66), switching tends to break when that name does not exist. Both checks seem quite small and not strictly necessary, but I'm not sure. Hence, not a PR.

**To Reproduce the latter behavior**

1. Get the xkb layout file ([make your own](https://wiki.archlinux.org/title/X_keyboard_extension#Using_keymap) or use [mine](https://pastebin.com/PmstRYWV));
3. Change `kb_layout` to `kb_file` for the relevant input device;
4. Run `hyprland-per-window-layout` (with layout number check commented out); 
5. Open 2 windows (e.g. terminal);
6. Type something in the 1st one (e.g. test);
7. Switch layout in the 2nd one, type something (e.g. тест);
8. Repeat steps 6 and 7 several times;
9. Layouts get mixed up.

**Expected behavior**
I expect them not to get mixed up, and that's what happens with [the aforementioned line](https://github.com/coffebar/hyprland-per-window-layout/blob/main/src/main.rs#L66) removed.

**Linux Distro (please complete the following information):**
 - nixos unstable (which shouldn't really matter here)

**Demo**
Here's a [quick demo](https://www.youtube.com/watch?v=ss4wPeCO1Rw) of what does and what should happen as well as the [log](https://pastebin.com/MS9aNqWu) obtained while making it.

**Comment by coffebar** [comment]
Hi, I will investigate this issue

**Comment by c0h2r** [comment]
Thanks! Also, I forgot to mention that if you decide to use the .xkb I provided, the layout switching there is done with `super+space`.

**Comment by coffebar** [comment]
please test the fix from the main branch

**Comment by c0h2r** [comment]
Works perfectly, thanks!
