### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gratural** [coffebar/hyprland-per-window-layout#5]
The language encoding is breaking in Wine applications.

**To Reproduce**
1. Launch any app under wine
2. Switch to another workspace and run any application and change the layout in that application
3. Then return to the first  with the application launched under the wine
4. Sometimes this bug occurs after 2 or 3 workspace switching.

Manjaro Stable, Kernel 6.1.31-2-MANJARO
Hyprland 0.26, xdg-desktop-portal-hyprland 0.3.1-1

"Input" section from my Hyprland.conf:
```
    kb_layout = us,ru
    kb_options = grp:win_space_toggle
    numlock_by_default = true
```

![250623_113844](https://github.com/coffebar/hyprland-per-window-layout/assets/3275410/e4903e4a-9f35-4450-8e7d-3131af7e9803)

**Comment by coffebar** [comment]
This software does nothing with encodings, it operates cli of the hyprland to switch layouts from your list. I can't help with your issue.

p.s. russians are not welcome here.

**Comment by gratural** [comment]
Nazi bastard, russian - are 30% of total users your gomo-rust crummy handicraft
