### ISSUE TITLE
Could you please describe what this app is doing? Couldn't figure out from readme

### ISSUE THREAD

**Issue by numfin** [coffebar/hyprland-per-window-layout#6]
Some visual examples or explanation would be nice. Thanks <3

**Comment by coffebar** [comment]
For example, you are coding in one language and chat in another one. When you're switching from IDE app to chat app, the keyboard layout follows the window focus as you switch it before when that window was in focus.

**Comment by numfin** [comment]
Oh, so its for keyboard layout. Couldnt figure it out 🥲
