### ISSUE TITLE
[BUG] Layout don't changes when switching workspace

### ISSUE THREAD

**Issue by ProMix0** [coffebar/hyprland-per-window-layout#7]
**Describe the bug**
When you switching workspaces, keyboard layout remains the same as in previously active window, regardless of current active window layout

**To Reproduce**
1. Setup two different windows in two different workspaces
2. Try to change layout in one window and switch to another workspace
3. You will got layout of the previous window

**Expected behavior**
Switching from another workspace will not change current window layout

**Linux Distro (please complete the following information):**
 Latest Arch (except waybar, nevermind)

**Additional context**
Saw it first time a months ago. Maybe a half year

**Comment by coffebar** [comment]
I believe you, but I cannot reproduce it. 
Please start hyprland-per-window-layout in debug mode in your Hyprland config:

### Replace 
```
exec-once = /usr/bin/hyprland-per-window-layout
```
with
```
exec-once = RUST_LOG='debug' /usr/bin/hyprland-per-window-layout > /tmp/hyprland-per-window-layout.log 2>&1
```
and check your hyprland-per-window-layout is not crashed when you see the bug, 
and make sure that  `activewindow` event fired when you switch workspace ( see /tmp/hyprland-per-window-layout.log ).

**Comment by ProMix0** [comment]
Actually, I did it in single workspace, so it's not the reason

What have I done:

- Start weston-terminal (1)
- Start alacritty (2)
- Type in 2 (en)
- Switch to 1
- Type in 1 (en)
- Change layout (and type, sure) (ru)
- Switch to 2
- Type in 2 (en)
- Change layout (ru)
- Switch to 1
- Type in 1 (ru)
- Change layout (en)
- Switch to 2
- Type in 2 **(en) - should be ru**

Complicated a bit, sorry. Actually I did just typing, changing layout and switching to another window. After a few attempts I got what I got

Log file attached
[hyprland-per-window-layout.log](https://github.com/coffebar/hyprland-per-window-layout/files/13335309/hyprland-per-window-layout.log)

**Comment by coffebar** [comment]
What do you have in *hyprland.conf* **input** section?

**Comment by ProMix0** [comment]
```
input {
    kb_layout = us,ru
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}
```

**Comment by coffebar** [comment]
It seems the problem related to wvkbd, it creates one more keyboard layout, that is not listed in `input {
    kb_layout = us,ru`, so hyprland can't switch to it. I created a fix, could you [install from source](https://github.com/coffebar/hyprland-per-window-layout#install-from-source) and check latest version before i will push it to aur?

**Comment by ProMix0** [comment]
Yes, seems like problem was solved
